version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "housingbackend"
    ports:
      - "5433:5432"
    volumes:
      - ./dataVolume2/postgres:/var/lib/postgresql/data
  housing:
    build: .
    image: housing
    environment:
      DEBUG: "true"
      COMPOSE: "true"
      DATABASE_CHOICE: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_USER: "postgres"
      DATABASE_NAME: "housingbackend"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: 5432
      DATABASE_DB: "postgres"
      ALLOWED_HOSTS: "0.0.0.0"
      DJANGO_SU_NAME: "admin"
      DJANGO_SU_EMAIL: "admin@housingbackend.com"
      DJANGO_SU_PASSWORD: "testuser"
      DJANGO_DB_NAME: "default"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/app

