"""housol URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


title = 'Housol API'
schema_view = get_schema_view(
    openapi.Info(
        title=title,
        default_version='v1',
        description="""Housol API.
                    You are currently on the `swagger-ui` view.
                    The `ReDoc` view can be found [here](/docs).
                    The swagger YAML document can be found [here](/swagger.yaml).
                    **Note**
                    1. User is required to send an authorization header using the token generated by `/token/auth` API
                    2. When sending the token to the API, include `JWT` in your header field. Example {"Authorization": "JWT token"}
                    3. The authorization header is required on all API's except: `/user/register`, `/token/refresh/`, `/token/auth/`
                    4. To get an authorization token, use the `/user/register` to register and login using `/token/auth/`
                  """,
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', RedirectView.as_view(url='/admin/login/?next=/')),
    path('users/', include('userinfo.urls')),
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('v1/swagger/ui', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui-2'),
    path('docs/', include_docs_urls(title=title)),
    path(r'series/', include('timeseries.urls')),
]
